apiVersion: v1 
kind: Service
metadata:
  name: {{ .Values.backend.label }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: {{ .Values.backend.label }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.port }}