apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongo.label }}
spec:
  replicas: {{ .Values.mongo.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mongo.label }} 
  template:
    metadata:
      labels:
        app: {{ .Values.mongo.label }}
    spec:
      containers:
      - name: {{ .Values.mongo.label }}
        image: {{ .Values.mongo.image.repository }}
        ports: 
          - containerPort: {{ .Values.mongo.service.port }}
