mongo:
  replicas: 1
  image: 
    repository: "mongo"
    dockerTag: "latest"
    pullPolicy: "Always"
  service:
    url: mongo.fluffyb.net
    type: ClusterIP
    port: 27017
  label: "MR_LVL5_M5_MONGODB"

backend:
  replicas: 1
  image: 
    repository: "git.sethsamuel.online/fluffy/mr_lvl5_m5_p1_back"
    pullPolicy: "Always"
  service:
    url: backm5.fluffyb.net
    type: ClusterIP
    port: 4000
  label: "MR_LVL5_M5_BACKEND"
